<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20160805060442 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_location (persistence_object_identifier VARCHAR(40) NOT NULL, name VARCHAR(255) NOT NULL, zipcode INT NOT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("CREATE TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_voucher (persistence_object_identifier VARCHAR(40) NOT NULL, location VARCHAR(40) DEFAULT NULL, username VARCHAR(255) NOT NULL, password VARCHAR(255) NOT NULL, validitymin INT NOT NULL, requesttime DATETIME DEFAULT NULL, INDEX IDX_A6B6C58C5E9E89CB (location), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_voucher ADD CONSTRAINT FK_A6B6C58C5E9E89CB FOREIGN KEY (location) REFERENCES weissheiten_coaching_gowiththeflowbasics_domain_model_location (persistence_object_identifier)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_voucher DROP FOREIGN KEY FK_A6B6C58C5E9E89CB");
		$this->addSql("DROP TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_location");
		$this->addSql("DROP TABLE weissheiten_coaching_gowiththeflowbasics_domain_model_voucher");
	}
}